"""Initial Sahil Rent Pay Schema Deployment

Revision ID: 45d2367bf66d
Revises: 
Create Date: 2026-06-01 17:27:05.062211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45d2367bf66d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.Enum('ADMIN', 'LANDLORD', 'CARETAKER', 'TENANT', name='roletype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_type'), ['role_type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('landlords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=150), nullable=True),
    sa.Column('mpesa_paybill_number', sa.String(length=50), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trial_end_date', sa.DateTime(), nullable=False),
    sa.Column('initials_prefix', sa.String(length=10), nullable=False),
    sa.CheckConstraint('processing_fee >= 0', name='check_positive_processing_fee'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlords_initials_prefix'), ['initials_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_landlords_trial_end_date'), ['trial_end_date'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    op.create_table('platform_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('default_processing_fee', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trial_is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_duration_days', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('default_processing_fee >= 0', name='check_positive_default_fee'),
    sa.CheckConstraint('trial_duration_days >= 0', name='check_positive_trial_days'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_settings_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('system_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caretakers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['landlords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caretakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caretakers_employer_id'), ['employer_id'], unique=False)

    op.create_table('charge_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('landlord_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_types_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_types_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('landlord_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('houses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('house_number', sa.String(length=50), nullable=False),
    sa.Column('base_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('VACANT', 'OCCUPIED', name='housestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('base_rent >= 0', name='check_positive_base_rent'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_houses_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_houses_house_number'), ['house_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_houses_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_houses_status'), ['status'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('house_id', sa.String(length=36), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('activation_token_expiry', sa.DateTime(), nullable=True),
    sa.CheckConstraint('deposit_amount >= 0', name='check_positive_deposit'),
    sa.CheckConstraint('move_out_date >= move_in_date', name='check_logical_dates'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_token')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_house_id'), ['house_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_id_number'), ['id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_is_archived'), ['is_archived'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='invoicestatus'), nullable=False),
    sa.Column('is_fine', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_amount >= 0', name='check_positive_invoice_total'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('bill_ref_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='mpesastatus'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('matched_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_positive_mpesa_amount'),
    sa.ForeignKeyConstraint(['matched_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_bill_ref_number'), ['bill_ref_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_is_claimed'), ['is_claimed'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_matched_tenant_id'), ['matched_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_status'), ['status'], unique=False)

    op.create_table('pending_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('charge_type_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_invoiced', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_positive_charge_amount'),
    sa.ForeignKeyConstraint(['charge_type_id'], ['charge_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_charges_charge_type_id'), ['charge_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_charges_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_charges_is_invoiced'), ['is_invoiced'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_charges_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('mpesa_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mpesa_transaction_id'], ['mpesa_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_user_id'), ['user_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mpesa_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_applied > 0', name='check_positive_allocation'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mpesa_transaction_id'], ['mpesa_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_mpesa_transaction_id'), ['mpesa_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_mpesa_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_deleted_at'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_created_at'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_deleted_at'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('pending_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_charges_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pending_charges_is_invoiced'))
        batch_op.drop_index(batch_op.f('ix_pending_charges_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_pending_charges_charge_type_id'))

    op.drop_table('pending_charges')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_matched_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_is_claimed'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_bill_ref_number'))

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_billing_month'))

    op.drop_table('invoices')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_is_archived'))
        batch_op.drop_index(batch_op.f('ix_tenants_id_number'))
        batch_op.drop_index(batch_op.f('ix_tenants_house_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_houses_status'))
        batch_op.drop_index(batch_op.f('ix_houses_property_id'))
        batch_op.drop_index(batch_op.f('ix_houses_house_number'))
        batch_op.drop_index(batch_op.f('ix_houses_deleted_at'))

    op.drop_table('houses')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_properties_deleted_at'))

    op.drop_table('properties')
    with op.batch_alter_table('charge_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_types_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_charge_types_deleted_at'))

    op.drop_table('charge_types')
    with op.batch_alter_table('caretakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caretakers_employer_id'))

    op.drop_table('caretakers')
    op.drop_table('system_admins')
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_settings_deleted_at'))

    op.drop_table('platform_settings')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_channel'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlords_trial_end_date'))
        batch_op.drop_index(batch_op.f('ix_landlords_initials_prefix'))

    op.drop_table('landlords')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_type'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
